ENVBIRONMENT_VALIABLES: dict = {
    "OPENAI_API_KEY" : "YOUR_OPENAI_API_KEY",
    "LANGCHAIN_TRACING_V2" : "true",
    "LANGCHAIN_PROJECT" : f"PolisJAPAN",
    "LANGCHAIN_ENDPOINT" : "https://api.smith.langchain.com",
    "LANGCHAIN_API_KEY" : "YOUR_LANGCHAIN_API_KEY",
    "AWS_ACCESS_KEY_ID" : "YOUR_AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY" : "YOUR_AWS_SECRET_ACCESS_KEY+MVm5o6r8vek",
    "AWS_DEFAULT_REGION" : "YOUR_AWS_DEFAULT_REGION",
} 
"""環境変数に自動セットする値"""